server:
  port: 6061
  servlet:
    context-path: /api

spring:
  autoconfigure:
    exclude:
      - org.springframework.ai.vectorstore.elasticsearch.autoconfigure.ElasticsearchVectorStoreAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/easymall?allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  task:
    scheduling:
      pool:
        size: 5
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  elasticsearch:
    uris: http://localhost:9200

mybatis:
  configuration:
    map-underscore-to-camel-case: true

project:
  folder: d:/webser/web_app/easymall/

admin:
  account: admin
  password: admin123

log:
  root:
    level: debug

upload:
  path: ${user.dir}/easymall-uploads
